// web/src/pages/archive-rule-traces/ArchiveRuleTracesPage.vue
<script setup lang="ts">
import { ElMessage, type FormInstance } from "element-plus";
import { ref } from "vue";

import { searchArchiveRuleTraces } from "@/shared/api/archive";
import type { ArchiveRuleTraceDto, ArchiveRuleType } from "@/shared/types/archive";

const ruleTypes: ArchiveRuleType[] = [
    "VALIDATION",
    "DERIVATION",
    "REFERENCE_CODE",
    "RETENTION",
    "ACCESS",
    "QUALITY",
    "TRANSFER",
    "FILING",
    "EXPORT",
];

const formRef = ref<FormInstance>();
const form = ref({
    schemeVersionId: undefined as number | undefined,
    triggerCode: "",
    objectTypeCode: "",
    objectId: undefined as number | undefined,
    ruleType: undefined as ArchiveRuleType | undefined,
    limit: 100,
});
const items = ref<ArchiveRuleTraceDto[]>([]);
const loading = ref(false);

async function submitSearch() {
    const valid = await formRef.value?.validate().catch(() => false);
    if (valid === false) return;
    loading.value = true;
    try {
        const response = await searchArchiveRuleTraces({
            schemeVersionId: form.value.schemeVersionId,
            triggerCode: form.value.triggerCode || undefined,
            objectTypeCode: form.value.objectTypeCode || undefined,
            objectId: form.value.objectId,
            ruleType: form.value.ruleType,
            limit: form.value.limit,
        });
        items.value = response.items;
    } catch (error) {
        ElMessage.error((error as Error).message);
    } finally {
        loading.value = false;
    }
}

function resetForm() {
    formRef.value?.resetFields();
}
</script>

<template>
    <section class="am-page">
        <div class="am-page__header"><h1>规则追踪</h1></div>
        <el-card class="am-page__filter" shadow="never">
            <el-form ref="formRef" :model="form" inline>
                <el-form-item label="治理版本" prop="schemeVersionId">
                    <el-input-number
                        v-model="form.schemeVersionId"
                        :min="1"
                        controls-position="right"
                    />
                </el-form-item>
                <el-form-item label="触发点" prop="triggerCode">
                    <el-input v-model="form.triggerCode" clearable />
                </el-form-item>
                <el-form-item label="对象类型" prop="objectTypeCode">
                    <el-input v-model="form.objectTypeCode" clearable />
                </el-form-item>
                <el-form-item label="对象 ID" prop="objectId">
                    <el-input-number v-model="form.objectId" :min="1" controls-position="right" />
                </el-form-item>
                <el-form-item label="规则类型" prop="ruleType">
                    <el-select v-model="form.ruleType" clearable style="width: 140px">
                        <el-option
                            v-for="value in ruleTypes"
                            :key="value"
                            :label="value"
                            :value="value"
                        />
                    </el-select>
                </el-form-item>
                <el-form-item label="条数" prop="limit">
                    <el-input-number
                        v-model="form.limit"
                        :min="1"
                        :max="500"
                        controls-position="right"
                    />
                </el-form-item>
                <el-form-item>
                    <el-button type="primary" :loading="loading" @click="submitSearch"
                        >查询</el-button
                    >
                    <el-button @click="resetForm">重置</el-button>
                </el-form-item>
            </el-form>
        </el-card>
        <el-card shadow="never">
            <el-table v-loading="loading" :data="items" row-key="id">
                <el-table-column prop="createdAt" label="时间" width="170" />
                <el-table-column prop="schemeVersionId" label="治理版本" width="100" />
                <el-table-column prop="triggerCode" label="触发点" width="130" />
                <el-table-column prop="objectTypeCode" label="对象类型" width="130" />
                <el-table-column prop="objectId" label="对象 ID" width="100" />
                <el-table-column prop="ruleCode" label="规则" width="160" />
                <el-table-column prop="ruleType" label="类型" width="120" />
                <el-table-column label="结果" width="90">
                    <template #default="{ row }">
                        <el-tag
                            :type="
                                row.blockingFlag ? 'danger' : row.matchedFlag ? 'primary' : 'info'
                            "
                        >
                            {{ row.blockingFlag ? "阻断" : row.matchedFlag ? "命中" : "跳过" }}
                        </el-tag>
                    </template>
                </el-table-column>
                <el-table-column prop="message" label="消息" />
            </el-table>
        </el-card>
    </section>
</template>

// web/src/pages/archive-rule-traces/ArchiveRuleTracesPage.tsx
import { useMutation } from "@tanstack/react-query";
import {
    Button,
    Card,
    Form,
    Input,
    InputNumber,
    message,
    Select,
    Space,
    Table,
    Tag,
    Typography,
} from "antd";
import type { TableColumnsType } from "antd";
import { useState } from "react";

import { searchArchiveRuleTraces } from "@/shared/api/archive";
import type { ArchiveRuleTraceDto, ArchiveRuleType } from "@/shared/types/archive";

const ruleTypes: ArchiveRuleType[] = [
    "VALIDATION",
    "DERIVATION",
    "REFERENCE_CODE",
    "RETENTION",
    "ACCESS",
    "QUALITY",
    "TRANSFER",
    "FILING",
    "EXPORT",
];

export function ArchiveRuleTracesPage() {
    const [form] = Form.useForm();
    const [items, setItems] = useState<ArchiveRuleTraceDto[]>([]);
    const searchMutation = useMutation({
        mutationFn: searchArchiveRuleTraces,
        onSuccess: (response) => setItems(response.items),
        onError: (error: Error) => message.error(error.message),
    });

    async function submitSearch() {
        const values = await form.validateFields();
        searchMutation.mutate({
            schemeVersionId: values.schemeVersionId,
            triggerCode: values.triggerCode,
            objectTypeCode: values.objectTypeCode,
            objectId: values.objectId,
            ruleType: values.ruleType,
            limit: values.limit ?? 100,
        });
    }

    const columns: TableColumnsType<ArchiveRuleTraceDto> = [
        { title: "时间", dataIndex: "createdAt", width: 170 },
        { title: "治理版本", dataIndex: "schemeVersionId", width: 100 },
        { title: "触发点", dataIndex: "triggerCode", width: 130 },
        { title: "对象类型", dataIndex: "objectTypeCode", width: 130 },
        { title: "对象 ID", dataIndex: "objectId", width: 100 },
        { title: "规则", dataIndex: "ruleCode", width: 160 },
        { title: "类型", dataIndex: "ruleType", width: 120 },
        {
            title: "结果",
            dataIndex: "matchedFlag",
            width: 90,
            render: (matched: boolean, row) => (
                <Tag color={row.blockingFlag ? "red" : matched ? "blue" : undefined}>
                    {row.blockingFlag ? "阻断" : matched ? "命中" : "跳过"}
                </Tag>
            ),
        },
        { title: "消息", dataIndex: "message" },
    ];

    return (
        <section className="am-page">
            <div className="am-page__header">
                <Typography.Title level={1}>规则追踪</Typography.Title>
            </div>
            <Card className="am-page__filter">
                <Form form={form} layout="inline" initialValues={{ limit: 100 }}>
                    <Form.Item label="治理版本" name="schemeVersionId">
                        <InputNumber min={1} />
                    </Form.Item>
                    <Form.Item label="触发点" name="triggerCode">
                        <Input allowClear />
                    </Form.Item>
                    <Form.Item label="对象类型" name="objectTypeCode">
                        <Input allowClear />
                    </Form.Item>
                    <Form.Item label="对象 ID" name="objectId">
                        <InputNumber min={1} />
                    </Form.Item>
                    <Form.Item label="规则类型" name="ruleType">
                        <Select
                            allowClear
                            options={ruleTypes.map((value) => ({ label: value, value }))}
                            style={{ width: 140 }}
                        />
                    </Form.Item>
                    <Form.Item label="条数" name="limit">
                        <InputNumber max={500} min={1} />
                    </Form.Item>
                    <Form.Item>
                        <Space>
                            <Button
                                loading={searchMutation.isPending}
                                type="primary"
                                onClick={() => void submitSearch()}
                            >
                                查询
                            </Button>
                            <Button onClick={() => form.resetFields()}>重置</Button>
                        </Space>
                    </Form.Item>
                </Form>
            </Card>
            <Card>
                <Table
                    columns={columns}
                    dataSource={items}
                    loading={searchMutation.isPending}
                    pagination={false}
                    rowKey="id"
                />
            </Card>
        </section>
    );
}
