// frontend/admin/src/pages/archive-categories/ArchiveCategoriesPage.vue
<script setup lang="ts">
import { computed } from "vue";

import { AmDataTable } from "@/shared/components/data-table";
import { usePermissionStore } from "@/stores/permissionStore";
import ArchiveCategoryScopeDialog from "./ArchiveCategoryScopeDialog.vue";
import ArchiveLineTablePanel from "./ArchiveLineTablePanel.vue";
import {
    fieldTypeLabels,
    managementModeLabels,
    useArchiveCategories,
} from "./useArchiveCategories";

const {
    buildTable,
    categories,
    categoryDialogOpen,
    categoryForm,
    categoryMode,
    fieldDialogOpen,
    fieldForm,
    fieldMode,
    fields,
    fonds,
    loading,
    openCreateCategory,
    openCreateField,
    openEditCategory,
    openEditField,
    parentOptions,
    removeCategory,
    removeField,
    saveCategory,
    saveField,
    saving,
    scopeDialog,
    selectedCategory,
    selectedCategoryId,
    treeData,
} = useArchiveCategories();

const permissionStore = usePermissionStore();
const canManageMetadata = computed(() => permissionStore.has("archive:metadata:manage"));
</script>

<template>
    <section class="am-page">
        <div class="am-page__header">
            <h1>档案分类</h1>
            <div>
                <el-button :disabled="loading || fonds.length === 0" @click="scopeDialog?.show()"
                    >全宗可用分类</el-button
                ><el-button type="primary" @click="openCreateCategory">新建分类</el-button
                ><el-button
                    v-if="selectedCategory?.tableStatus === 'NOT_BUILT'"
                    :loading="saving"
                    @click="buildTable"
                    >生成动态表</el-button
                >
            </div>
        </div>
        <el-row :gutter="16">
            <el-col :xs="24" :lg="7"
                ><el-card v-loading="loading" header="分类树" shadow="never"
                    ><el-empty
                        v-if="treeData.length === 0"
                        description="暂无分类，请新建"
                        :image-size="48" /><el-tree
                        v-else
                        :data="treeData"
                        node-key="id"
                        default-expand-all
                        highlight-current
                        :current-node-key="selectedCategoryId"
                        @node-click="(node) => (selectedCategoryId = node.id)" /></el-card
            ></el-col>
            <el-col :xs="24" :lg="17"
                ><el-card shadow="never"
                    ><template #header
                        ><div class="card-header">
                            <span>{{
                                selectedCategory
                                    ? `${selectedCategory.categoryName}（${selectedCategory.categoryCode}）`
                                    : "字段定义"
                            }}</span>
                            <div v-if="selectedCategory">
                                <el-text type="info">{{
                                    managementModeLabels[selectedCategory.managementMode]
                                }}</el-text
                                ><el-text v-if="selectedCategory.itemTableName" tag="code">{{
                                    selectedCategory.itemTableName
                                }}</el-text
                                ><el-button size="small" @click="openCreateField"
                                    >新建字段</el-button
                                ><el-button size="small" @click="openEditCategory">编辑</el-button
                                ><el-button size="small" type="danger" plain @click="removeCategory"
                                    >删除</el-button
                                >
                            </div>
                        </div></template
                    >
                    <AmDataTable
                        :data="fields"
                        row-key="id"
                        :columns="[
                            { key: 'fieldCode', label: '字段编码', width: 160, sortable: true },
                            { key: 'fieldName', label: '字段名称', sortable: true },
                            { key: 'fieldType', label: '字段类型', width: 100, sortable: true },
                            { key: 'archiveLevel', label: '层级', width: 80, sortable: true },
                            { key: 'listVisible', label: '列表显示', width: 100, sortable: true },
                            { key: 'enabled', label: '启用', width: 80, sortable: true },
                            { key: 'actions', label: '操作', width: 130 },
                        ]"
                    >
                        <template #cell-fieldType="{ row }">
                            {{ fieldTypeLabels[row.fieldType] ?? row.fieldType }}
                        </template>
                        <template #cell-archiveLevel="{ row }">
                            {{ row.archiveLevel === "VOLUME" ? "案卷" : "条目" }}
                        </template>
                        <template #cell-listVisible="{ row }">
                            {{ row.listVisible ? "是" : "否" }}
                        </template>
                        <template #cell-enabled="{ row }">
                            <el-tag :type="row.enabled ? 'success' : 'info'">
                                {{ row.enabled ? "启用" : "停用" }}
                            </el-tag>
                        </template>
                        <template #cell-actions="{ row }">
                            <el-button link type="primary" @click="openEditField(row)"
                                >编辑</el-button
                            >
                            <el-button link type="danger" @click="removeField(row)">删除</el-button>
                        </template>
                    </AmDataTable>
                </el-card>
                <div v-if="canManageMetadata && selectedCategoryId" class="line-table-panel">
                    <ArchiveLineTablePanel :category-id="selectedCategoryId" />
                </div>
            </el-col>
        </el-row>
        <el-dialog
            v-model="categoryDialogOpen"
            :title="categoryMode === 'create' ? '新建分类' : '编辑分类'"
            width="520"
            ><el-form :model="categoryForm" label-position="top"
                ><el-form-item label="父级分类"
                    ><el-select v-model="categoryForm.parentId" clearable
                        ><el-option
                            v-for="item in parentOptions"
                            :key="item.id"
                            :label="item.categoryName"
                            :value="item.id" /></el-select></el-form-item
                ><el-form-item label="分类编码" required
                    ><el-input v-model="categoryForm.categoryCode" /></el-form-item
                ><el-form-item label="分类名称" required
                    ><el-input v-model="categoryForm.categoryName" /></el-form-item
                ><el-form-item label="管理模式"
                    ><el-select v-model="categoryForm.managementMode"
                        ><el-option
                            v-for="(label, value) in managementModeLabels"
                            :key="value"
                            :label="label"
                            :value="value" /></el-select></el-form-item
                ><el-row :gutter="16"
                    ><el-col :span="12"
                        ><el-form-item label="排序"
                            ><el-input-number
                                v-model="categoryForm.sortOrder"
                                :min="0" /></el-form-item></el-col
                    ><el-col :span="12"
                        ><el-form-item label="启用"
                            ><el-switch
                                v-model="
                                    categoryForm.enabled
                                " /></el-form-item></el-col></el-row></el-form
            ><template #footer
                ><el-button @click="categoryDialogOpen = false">取消</el-button
                ><el-button type="primary" :loading="saving" @click="saveCategory"
                    >确定</el-button
                ></template
            ></el-dialog
        >
        <el-dialog
            v-model="fieldDialogOpen"
            :title="fieldMode === 'create' ? '新建字段' : '编辑字段'"
            width="640"
            ><el-form :model="fieldForm" label-position="top"
                ><el-row :gutter="16"
                    ><el-col :span="12"
                        ><el-form-item label="层级"
                            ><el-select v-model="fieldForm.archiveLevel"
                                ><el-option label="条目" value="ITEM" /><el-option
                                    label="案卷"
                                    value="VOLUME" /></el-select></el-form-item></el-col
                    ><el-col :span="12"
                        ><el-form-item label="字段类型"
                            ><el-select v-model="fieldForm.fieldType"
                                ><el-option
                                    v-for="(label, value) in fieldTypeLabels"
                                    :key="value"
                                    :label="label"
                                    :value="value" /></el-select></el-form-item></el-col></el-row
                ><el-row :gutter="16"
                    ><el-col :span="12"
                        ><el-form-item label="字段编码" required
                            ><el-input v-model="fieldForm.fieldCode" /></el-form-item></el-col
                    ><el-col :span="12"
                        ><el-form-item label="字段名称" required
                            ><el-input
                                v-model="fieldForm.fieldName" /></el-form-item></el-col></el-row
                ><el-form-item v-if="fieldForm.fieldType === 'TEXT'" label="文本长度"
                    ><el-input-number v-model="fieldForm.textLength" :min="1" /></el-form-item
                ><el-row v-if="fieldForm.fieldType === 'DECIMAL'" :gutter="16"
                    ><el-col :span="12"
                        ><el-form-item label="总位数"
                            ><el-input-number
                                v-model="fieldForm.decimalPrecision"
                                :min="1" /></el-form-item></el-col
                    ><el-col :span="12"
                        ><el-form-item label="小数位"
                            ><el-input-number
                                v-model="fieldForm.decimalScale"
                                :min="0" /></el-form-item></el-col></el-row
                ><el-divider>显示与搜索</el-divider>
                <div class="switch-grid">
                    <el-checkbox v-model="fieldForm.listVisible">列表显示</el-checkbox
                    ><el-checkbox v-model="fieldForm.detailVisible">详情显示</el-checkbox
                    ><el-checkbox v-model="fieldForm.editVisible">编辑可见</el-checkbox
                    ><el-checkbox v-model="fieldForm.exactSearchable">精确检索</el-checkbox
                    ><el-checkbox v-model="fieldForm.dataScopeFilterable"
                        >可用于数据范围</el-checkbox
                    ><el-checkbox v-model="fieldForm.enabled">启用</el-checkbox>
                </div></el-form
            ><template #footer
                ><el-button @click="fieldDialogOpen = false">取消</el-button
                ><el-button type="primary" :loading="saving" @click="saveField"
                    >确定</el-button
                ></template
            ></el-dialog
        >
        <ArchiveCategoryScopeDialog ref="scopeDialog" :fonds="fonds" :categories="categories" />
    </section>
</template>

<style scoped>
.card-header,
.card-header > div {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 8px;
    flex-wrap: wrap;
}
.switch-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 12px;
}
.line-table-panel {
    margin-top: 16px;
}
</style>

// web/src/pages/archive-categories/ArchiveCategoriesPage.tsx
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
    Button,
    Card,
    Col,
    Form,
    Input,
    InputNumber,
    message,
    Modal,
    Popconfirm,
    Row,
    Select,
    Space,
    Switch,
    Table,
    Tag,
    Tree,
    Typography,
} from "antd";
import type { DataNode } from "antd/es/tree";
import type { TableColumnsType } from "antd";
import { useEffect, useState } from "react";

import {
    buildArchiveCategoryTable,
    createArchiveCategory,
    deleteArchiveCategory,
    listArchiveCategories,
    listArchiveFields,
    updateArchiveCategory,
} from "@/shared/api/archive";
import type {
    ArchiveCategoryDto,
    ArchiveFieldDto,
    ArchiveManagementMode,
} from "@/shared/types/archive";

const categoryQueryKey = ["archive-categories"] as const;

const managementModeLabels: Record<ArchiveManagementMode, string> = {
    ITEM_ONLY: "仅允许著录条目",
    VOLUME_ITEM: "可建卷并著录条目",
};

const fieldTypeLabels: Record<string, string> = {
    TEXT: "文本",
    INTEGER: "整数",
    DECIMAL: "小数",
    DATE: "日期",
    DATETIME: "日期时间",
};

const fieldColumns: TableColumnsType<ArchiveFieldDto> = [
    { title: "字段编码", dataIndex: "fieldCode", key: "fieldCode", width: 160 },
    { title: "字段名称", dataIndex: "fieldName", key: "fieldName" },
    {
        title: "字段类型",
        dataIndex: "fieldType",
        key: "fieldType",
        width: 100,
        render: (v: string) => fieldTypeLabels[v] ?? v,
    },
    {
        title: "层级",
        dataIndex: "archiveLevel",
        key: "archiveLevel",
        width: 80,
        render: (v: string) => (v === "VOLUME" ? "案卷" : "条目"),
    },
    {
        title: "列表显示",
        dataIndex: "listVisible",
        key: "listVisible",
        width: 100,
        render: (v: boolean) => (v ? "是" : "否"),
    },
    {
        title: "启用",
        dataIndex: "enabled",
        key: "enabled",
        width: 80,
        render: (v: boolean) => <Tag color={v ? "green" : "default"}>{v ? "启用" : "停用"}</Tag>,
    },
];

function buildCategoryTree(categories: ArchiveCategoryDto[]): DataNode[] {
    const nodeMap = new Map<number, DataNode>();
    const roots: DataNode[] = [];

    for (const cat of categories) {
        nodeMap.set(cat.id, {
            key: cat.id,
            title: `${cat.categoryName}（${cat.categoryCode}）`,
        });
    }

    for (const cat of categories) {
        const node = nodeMap.get(cat.id)!;
        if (cat.parentId != null) {
            const parent = nodeMap.get(cat.parentId);
            if (parent) {
                parent.children = [...(parent.children ?? []), node];
                continue;
            }
        }
        roots.push(node);
    }

    return roots;
}

export function ArchiveCategoriesPage() {
    const queryClient = useQueryClient();
    const [selectedCategoryId, setSelectedCategoryId] = useState<number | null>(null);
    const [modalOpen, setModalOpen] = useState(false);
    const [modalMode, setModalMode] = useState<"create" | "edit">("create");
    const [editingCategory, setEditingCategory] = useState<ArchiveCategoryDto | null>(null);
    const [form] = Form.useForm();

    const categoriesQuery = useQuery({
        queryKey: categoryQueryKey,
        queryFn: () => listArchiveCategories(),
    });

    const fieldsQuery = useQuery({
        queryKey: ["archive-fields", selectedCategoryId],
        queryFn: () => listArchiveFields(selectedCategoryId!),
        enabled: selectedCategoryId != null,
    });

    const createMutation = useMutation({
        mutationFn: createArchiveCategory,
        onSuccess: () => {
            message.success("分类创建成功");
            queryClient.invalidateQueries({ queryKey: categoryQueryKey });
            handleModalClose();
        },
        onError: (e: Error) => message.error(e.message),
    });

    const updateMutation = useMutation({
        mutationFn: ({
            id,
            payload,
        }: {
            id: number;
            payload: Parameters<typeof updateArchiveCategory>[1];
        }) => updateArchiveCategory(id, payload),
        onSuccess: () => {
            message.success("分类更新成功");
            queryClient.invalidateQueries({ queryKey: categoryQueryKey });
            handleModalClose();
        },
        onError: (e: Error) => message.error(e.message),
    });

    const deleteMutation = useMutation({
        mutationFn: (id: number) => deleteArchiveCategory(id),
        onSuccess: () => {
            message.success("分类已删除");
            if (selectedCategoryId === deleteMutation.variables) {
                setSelectedCategoryId(null);
            }
            queryClient.invalidateQueries({ queryKey: categoryQueryKey });
        },
        onError: (e: Error) => message.error(e.message),
    });

    const buildTableMutation = useMutation({
        mutationFn: (categoryId: number) => buildArchiveCategoryTable(categoryId),
        onSuccess: () => {
            message.success("动态表已生成");
            queryClient.invalidateQueries({ queryKey: categoryQueryKey });
        },
        onError: (e: Error) => message.error(e.message),
    });

    const categories = categoriesQuery.data?.items ?? [];
    const selectedCategory = categories.find((c) => c.id === selectedCategoryId);

    useEffect(() => {
        const exists = categories.some((c) => c.id === selectedCategoryId);
        if (!exists) {
            setSelectedCategoryId(categories.length > 0 ? categories[0].id : null);
        }
    }, [categories, selectedCategoryId]);

    const treeData = buildCategoryTree(categories);

    function handleModalClose() {
        setModalOpen(false);
        setEditingCategory(null);
        form.resetFields();
    }

    function openCreateModal(parentId?: number) {
        setModalMode("create");
        setEditingCategory(null);
        form.resetFields();
        form.setFieldsValue({
            parentId: parentId ?? undefined,
            enabled: true,
            sortOrder: 0,
            managementMode: "ITEM_ONLY",
        });
        setModalOpen(true);
    }

    function openEditModal(category: ArchiveCategoryDto) {
        setModalMode("edit");
        setEditingCategory(category);
        form.setFieldsValue({
            parentId: category.parentId ?? undefined,
            categoryCode: category.categoryCode,
            categoryName: category.categoryName,
            managementMode: category.managementMode,
            enabled: category.enabled,
            sortOrder: category.sortOrder,
        });
        setModalOpen(true);
    }

    async function handleSubmit() {
        const values = await form.validateFields();
        const payload = {
            parentId: values.parentId ?? undefined,
            categoryCode: values.categoryCode,
            categoryName: values.categoryName,
            managementMode: values.managementMode,
            enabled: values.enabled ?? true,
            sortOrder: values.sortOrder ?? 0,
        };
        if (modalMode === "create") {
            createMutation.mutate(payload);
        } else if (editingCategory) {
            updateMutation.mutate({
                id: editingCategory.id,
                payload: payload as Parameters<typeof updateArchiveCategory>[1],
            });
        }
    }

    const hasSelectedCategory = selectedCategory != null;

    return (
        <section className="am-page">
            <div className="am-page__header">
                <Typography.Title level={1}>档案分类</Typography.Title>
                <Space>
                    <Button
                        type="primary"
                        onClick={() => openCreateModal(selectedCategoryId ?? undefined)}
                    >
                        新建分类
                    </Button>
                    {hasSelectedCategory && selectedCategory.tableStatus === "NOT_BUILT" && (
                        <Button
                            loading={buildTableMutation.isPending}
                            onClick={() => buildTableMutation.mutate(selectedCategory.id)}
                        >
                            生成动态表
                        </Button>
                    )}
                </Space>
            </div>
            <Row gutter={[16, 16]}>
                <Col xs={24} lg={7}>
                    <Card title="分类树" loading={categoriesQuery.isLoading}>
                        {treeData.length === 0 && !categoriesQuery.isLoading ? (
                            <Typography.Text type="secondary">暂无分类，请新建</Typography.Text>
                        ) : (
                            <Tree
                                blockNode
                                defaultExpandAll
                                selectedKeys={
                                    selectedCategoryId != null ? [selectedCategoryId] : []
                                }
                                treeData={treeData}
                                onSelect={(keys) => {
                                    if (keys.length > 0) {
                                        setSelectedCategoryId(keys[0] as number);
                                    }
                                }}
                            />
                        )}
                    </Card>
                </Col>
                <Col xs={24} lg={17}>
                    <Card
                        title={
                            hasSelectedCategory
                                ? `${selectedCategory.categoryName}（${selectedCategory.categoryCode}）`
                                : "字段定义"
                        }
                        loading={fieldsQuery.isLoading}
                        extra={
                            hasSelectedCategory && (
                                <Space wrap>
                                    <Typography.Text type="secondary">
                                        {managementModeLabels[selectedCategory.managementMode]}
                                    </Typography.Text>
                                    {selectedCategory.tableStatus === "BUILT" &&
                                        selectedCategory.itemTableName && (
                                            <Typography.Text code>
                                                {selectedCategory.itemTableName}
                                            </Typography.Text>
                                        )}
                                    {selectedCategory.tableStatus === "BUILT" &&
                                        selectedCategory.volumeTableName && (
                                            <Typography.Text code>
                                                {selectedCategory.volumeTableName}
                                            </Typography.Text>
                                        )}
                                    <Button
                                        size="small"
                                        onClick={() => openEditModal(selectedCategory)}
                                    >
                                        编辑
                                    </Button>
                                    <Popconfirm
                                        title="确定删除此分类？"
                                        onConfirm={() => deleteMutation.mutate(selectedCategory.id)}
                                        okText="删除"
                                        cancelText="取消"
                                    >
                                        <Button
                                            size="small"
                                            danger
                                            loading={deleteMutation.isPending}
                                        >
                                            删除
                                        </Button>
                                    </Popconfirm>
                                </Space>
                            )
                        }
                    >
                        <Table<ArchiveFieldDto>
                            columns={fieldColumns}
                            dataSource={fieldsQuery.data?.items ?? []}
                            loading={fieldsQuery.isLoading}
                            pagination={false}
                            rowKey="id"
                            locale={{
                                emptyText: hasSelectedCategory ? "暂无字段" : "请在左侧选择分类",
                            }}
                        />
                    </Card>
                </Col>
            </Row>

            <Modal
                title={modalMode === "create" ? "新建分类" : "编辑分类"}
                open={modalOpen}
                onOk={handleSubmit}
                onCancel={handleModalClose}
                confirmLoading={createMutation.isPending || updateMutation.isPending}
                destroyOnClose
            >
                <Form form={form} layout="vertical" preserve={false}>
                    <Form.Item name="parentId" label="父级分类">
                        <Select
                            allowClear
                            placeholder="留空则为根分类"
                            options={categories
                                .filter(
                                    (c) => editingCategory == null || c.id !== editingCategory.id,
                                )
                                .map((c) => ({
                                    label: `${c.categoryName}（${c.categoryCode}）`,
                                    value: c.id,
                                }))}
                        />
                    </Form.Item>
                    <Form.Item
                        name="categoryCode"
                        label="分类编码"
                        rules={[{ required: true, message: "请输入分类编码" }]}
                    >
                        <Input placeholder="例如：project" />
                    </Form.Item>
                    <Form.Item
                        name="categoryName"
                        label="分类名称"
                        rules={[{ required: true, message: "请输入分类名称" }]}
                    >
                        <Input placeholder="例如：项目档案" />
                    </Form.Item>
                    <Form.Item name="managementMode" label="管理模式" rules={[{ required: true }]}>
                        <Select
                            options={Object.entries(managementModeLabels).map(([value, label]) => ({
                                value,
                                label,
                            }))}
                        />
                    </Form.Item>
                    <Row gutter={16}>
                        <Col span={12}>
                            <Form.Item name="sortOrder" label="排序">
                                <InputNumber min={0} style={{ width: "100%" }} />
                            </Form.Item>
                        </Col>
                        <Col span={12}>
                            <Form.Item name="enabled" label="启用" valuePropName="checked">
                                <Switch checkedChildren="启用" unCheckedChildren="停用" />
                            </Form.Item>
                        </Col>
                    </Row>
                </Form>
            </Modal>
        </section>
    );
}
