// web/src/pages/archive-rules/ArchiveRulesPage.tsx
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
    Button,
    Card,
    Form,
    Input,
    InputNumber,
    message,
    Modal,
    Select,
    Space,
    Switch,
    Table,
    Tag,
    Typography,
} from "antd";
import type { TableColumnsType } from "antd";
import { useState } from "react";

import {
    createArchiveRule,
    disableArchiveRule,
    enableArchiveRule,
    executeArchiveRules,
    listArchiveRules,
    publishArchiveRule,
} from "@/shared/api/archive";
import type {
    ArchiveRuleDecisionDto,
    ArchiveRuleDto,
    ArchiveRuleEffectType,
    ArchiveRuleStatus,
    ArchiveRuleType,
} from "@/shared/types/archive";

const ruleTypes: ArchiveRuleType[] = [
    "VALIDATION",
    "DERIVATION",
    "REFERENCE_CODE",
    "RETENTION",
    "ACCESS",
    "QUALITY",
    "TRANSFER",
    "FILING",
    "EXPORT",
];

const effectTypes: ArchiveRuleEffectType[] = [
    "VALIDATION_ERROR",
    "WARNING",
    "SUGGEST_VALUE",
    "DERIVED_VALUE",
    "REQUIRE_REVIEW",
    "REQUIRE_QUALITY_CHECK",
    "DENY_ACCESS",
    "MASK_FIELD",
    "INCLUDE_IN_PACKAGE",
];

export function ArchiveRulesPage() {
    const queryClient = useQueryClient();
    const [schemeVersionId, setSchemeVersionId] = useState<number>();
    const [status, setStatus] = useState<ArchiveRuleStatus>();
    const [ruleModalOpen, setRuleModalOpen] = useState(false);
    const [executeModalOpen, setExecuteModalOpen] = useState(false);
    const [decisions, setDecisions] = useState<ArchiveRuleDecisionDto[]>([]);
    const [ruleForm] = Form.useForm();
    const [executeForm] = Form.useForm();

    const rulesQuery = useQuery({
        queryKey: ["archive-rules", schemeVersionId, status],
        queryFn: () => listArchiveRules(schemeVersionId!, status),
        enabled: schemeVersionId != null,
    });

    const createMutation = useMutation({
        mutationFn: createArchiveRule,
        onSuccess: () => {
            message.success("规则已创建");
            setRuleModalOpen(false);
            ruleForm.resetFields();
            queryClient.invalidateQueries({ queryKey: ["archive-rules"] });
        },
        onError: (error: Error) => message.error(error.message),
    });

    const publishMutation = useMutation({
        mutationFn: publishArchiveRule,
        onSuccess: () => {
            message.success("规则已发布");
            queryClient.invalidateQueries({ queryKey: ["archive-rules"] });
        },
        onError: (error: Error) => message.error(error.message),
    });

    const enabledMutation = useMutation({
        mutationFn: ({ id, enabled }: { id: number; enabled: boolean }) =>
            enabled ? enableArchiveRule(id) : disableArchiveRule(id),
        onSuccess: () => queryClient.invalidateQueries({ queryKey: ["archive-rules"] }),
        onError: (error: Error) => message.error(error.message),
    });

    const executeMutation = useMutation({
        mutationFn: executeArchiveRules,
        onSuccess: (response) => {
            setDecisions(response.items);
            message.success("规则试算完成");
        },
        onError: (error: Error) => message.error(error.message),
    });

    async function submitRule() {
        const values = await ruleForm.validateFields();
        createMutation.mutate({
            schemeVersionId: values.schemeVersionId,
            ruleCode: values.ruleCode,
            ruleName: values.ruleName,
            ruleType: values.ruleType,
            triggerCode: values.triggerCode,
            scopeFondsCode: values.scopeFondsCode,
            scopeCategoryCode: values.scopeCategoryCode,
            scopeArchiveLevel: values.scopeArchiveLevel,
            priority: values.priority ?? 0,
            conditionJson: parseJson(values.conditionJson),
            enabled: values.enabled ?? true,
            effects: [
                {
                    effectType: values.effectType,
                    effectOrder: 0,
                    effectParams: parseJson(values.effectParams || "{}"),
                },
            ],
        });
    }

    async function submitExecute() {
        const values = await executeForm.validateFields();
        executeMutation.mutate({
            schemeVersionId: values.schemeVersionId,
            triggerCode: values.triggerCode,
            fondsCode: values.fondsCode,
            categoryCode: values.categoryCode,
            objectTypeCode: values.objectTypeCode,
            archiveLevel: values.archiveLevel,
            facts: parseJson(values.facts),
            includeSkipped: values.includeSkipped ?? false,
            recordTrace: values.recordTrace ?? false,
        });
    }

    const columns: TableColumnsType<ArchiveRuleDto> = [
        { title: "编码", dataIndex: "ruleCode", width: 180 },
        { title: "名称", dataIndex: "ruleName" },
        { title: "类型", dataIndex: "ruleType", width: 130 },
        { title: "触发点", dataIndex: "triggerCode", width: 130 },
        { title: "优先级", dataIndex: "priority", width: 90 },
        {
            title: "状态",
            dataIndex: "status",
            width: 100,
            render: (value: ArchiveRuleStatus) => (
                <Tag color={value === "PUBLISHED" ? "blue" : undefined}>
                    {value === "PUBLISHED" ? "已发布" : "草稿"}
                </Tag>
            ),
        },
        {
            title: "启用",
            dataIndex: "enabled",
            width: 90,
            render: (enabled: boolean, row) => (
                <Switch
                    checked={enabled}
                    size="small"
                    onChange={(checked) => enabledMutation.mutate({ id: row.id, enabled: checked })}
                />
            ),
        },
        {
            title: "操作",
            width: 110,
            render: (_, row) => (
                <Button
                    disabled={row.status !== "DRAFT"}
                    size="small"
                    onClick={() => publishMutation.mutate(row.id)}
                >
                    发布
                </Button>
            ),
        },
    ];

    return (
        <section className="am-page">
            <div className="am-page__header">
                <Typography.Title level={1}>本地规则</Typography.Title>
                <Space>
                    <InputNumber
                        min={1}
                        placeholder="治理版本 ID"
                        value={schemeVersionId}
                        onChange={(value) => setSchemeVersionId(value ?? undefined)}
                    />
                    <Select
                        allowClear
                        placeholder="状态"
                        style={{ width: 120 }}
                        value={status}
                        options={[
                            { label: "草稿", value: "DRAFT" },
                            { label: "已发布", value: "PUBLISHED" },
                        ]}
                        onChange={setStatus}
                    />
                    <Button type="primary" onClick={() => setRuleModalOpen(true)}>
                        新建规则
                    </Button>
                    <Button onClick={() => setExecuteModalOpen(true)}>规则试算</Button>
                </Space>
            </div>
            <Card>
                <Table
                    columns={columns}
                    dataSource={rulesQuery.data?.items ?? []}
                    loading={rulesQuery.isLoading}
                    pagination={false}
                    rowKey="id"
                />
            </Card>
            <Modal
                open={ruleModalOpen}
                title="新建规则"
                width={720}
                onCancel={() => setRuleModalOpen(false)}
                onOk={() => void submitRule()}
            >
                <Form
                    form={ruleForm}
                    layout="vertical"
                    initialValues={{
                        ruleType: "VALIDATION",
                        effectType: "VALIDATION_ERROR",
                        enabled: true,
                        priority: 0,
                        conditionJson:
                            '{"field":"fixed.archiveYear","operator":"GTE","value":2020}',
                        effectParams: '{"message":"规则命中"}',
                    }}
                >
                    <Form.Item
                        label="治理版本 ID"
                        name="schemeVersionId"
                        rules={[{ required: true }]}
                    >
                        <InputNumber min={1} style={{ width: "100%" }} />
                    </Form.Item>
                    <Form.Item label="规则编码" name="ruleCode" rules={[{ required: true }]}>
                        <Input />
                    </Form.Item>
                    <Form.Item label="规则名称" name="ruleName" rules={[{ required: true }]}>
                        <Input />
                    </Form.Item>
                    <Form.Item label="规则类型" name="ruleType">
                        <Select options={ruleTypes.map((value) => ({ label: value, value }))} />
                    </Form.Item>
                    <Form.Item label="触发点" name="triggerCode" rules={[{ required: true }]}>
                        <Input placeholder="BEFORE_SAVE" />
                    </Form.Item>
                    <Form.Item label="优先级" name="priority">
                        <InputNumber style={{ width: "100%" }} />
                    </Form.Item>
                    <Form.Item
                        label="条件树 JSON"
                        name="conditionJson"
                        rules={[{ required: true }]}
                    >
                        <Input.TextArea rows={5} />
                    </Form.Item>
                    <Form.Item label="effect 类型" name="effectType">
                        <Select options={effectTypes.map((value) => ({ label: value, value }))} />
                    </Form.Item>
                    <Form.Item label="effect 参数 JSON" name="effectParams">
                        <Input.TextArea rows={3} />
                    </Form.Item>
                    <Form.Item label="启用" name="enabled" valuePropName="checked">
                        <Switch />
                    </Form.Item>
                </Form>
            </Modal>
            <Modal
                open={executeModalOpen}
                title="规则试算"
                width={760}
                onCancel={() => setExecuteModalOpen(false)}
                onOk={() => void submitExecute()}
            >
                <Form
                    form={executeForm}
                    layout="vertical"
                    initialValues={{
                        schemeVersionId,
                        triggerCode: "BEFORE_SAVE",
                        objectTypeCode: "ARCHIVE_ITEM",
                        archiveLevel: "ITEM",
                        facts: '{"fixed.archiveYear":2026}',
                        includeSkipped: false,
                        recordTrace: false,
                    }}
                >
                    <Form.Item
                        label="治理版本 ID"
                        name="schemeVersionId"
                        rules={[{ required: true }]}
                    >
                        <InputNumber min={1} style={{ width: "100%" }} />
                    </Form.Item>
                    <Form.Item label="触发点" name="triggerCode" rules={[{ required: true }]}>
                        <Input />
                    </Form.Item>
                    <Form.Item label="对象类型" name="objectTypeCode">
                        <Input />
                    </Form.Item>
                    <Form.Item label="对象层级" name="archiveLevel">
                        <Select
                            options={[
                                { label: "条目", value: "ITEM" },
                                { label: "案卷", value: "VOLUME" },
                            ]}
                        />
                    </Form.Item>
                    <Form.Item label="事实 JSON" name="facts" rules={[{ required: true }]}>
                        <Input.TextArea rows={5} />
                    </Form.Item>
                    <Form.Item label="返回未命中" name="includeSkipped" valuePropName="checked">
                        <Switch />
                    </Form.Item>
                    <Form.Item label="保存追踪" name="recordTrace" valuePropName="checked">
                        <Switch />
                    </Form.Item>
                </Form>
                <Table
                    columns={[
                        { title: "规则", dataIndex: "ruleCode" },
                        {
                            title: "命中",
                            dataIndex: "matched",
                            width: 80,
                            render: (v) => (v ? "是" : "否"),
                        },
                        { title: "级别", dataIndex: "severity", width: 90 },
                        {
                            title: "阻断",
                            dataIndex: "blocking",
                            width: 80,
                            render: (v) => (v ? "是" : "否"),
                        },
                        { title: "消息", dataIndex: "message" },
                    ]}
                    dataSource={decisions}
                    pagination={false}
                    rowKey={(row) => `${row.ruleId ?? row.ruleCode}-${row.matched}`}
                    size="small"
                />
            </Modal>
        </section>
    );
}

function parseJson(value: string) {
    try {
        return JSON.parse(value || "{}") as Record<string, unknown>;
    } catch {
        throw new Error("JSON 格式不正确");
    }
}

// web/src/pages/archive-rules/ArchiveRulesPage.vue
<script setup lang="ts">
import { ElMessage, type FormInstance } from "element-plus";
import { onMounted, ref, watch } from "vue";

import {
    createArchiveRule,
    disableArchiveRule,
    enableArchiveRule,
    executeArchiveRules,
    listArchiveRules,
    publishArchiveRule,
} from "@/shared/api/archive";
import type {
    ArchiveLevel,
    ArchiveRuleDecisionDto,
    ArchiveRuleDto,
    ArchiveRuleEffectType,
    ArchiveRuleStatus,
    ArchiveRuleType,
} from "@/shared/types/archive";

const ruleTypes: ArchiveRuleType[] = [
    "VALIDATION",
    "DERIVATION",
    "REFERENCE_CODE",
    "RETENTION",
    "ACCESS",
    "QUALITY",
    "TRANSFER",
    "FILING",
    "EXPORT",
];
const effectTypes: ArchiveRuleEffectType[] = [
    "VALIDATION_ERROR",
    "WARNING",
    "SUGGEST_VALUE",
    "DERIVED_VALUE",
    "REQUIRE_REVIEW",
    "REQUIRE_QUALITY_CHECK",
    "DENY_ACCESS",
    "MASK_FIELD",
    "INCLUDE_IN_PACKAGE",
];

const schemeVersionId = ref<number>();
const status = ref<ArchiveRuleStatus>();
const rules = ref<ArchiveRuleDto[]>([]);
const loading = ref(false);
const ruleModalOpen = ref(false);
const executeModalOpen = ref(false);
const ruleSubmitting = ref(false);
const executeSubmitting = ref(false);
const ruleFormRef = ref<FormInstance>();
const executeFormRef = ref<FormInstance>();
const decisions = ref<ArchiveRuleDecisionDto[]>([]);
const ruleForm = ref(defaultRuleForm());
const executeForm = ref(defaultExecuteForm());

function defaultRuleForm() {
    return {
        schemeVersionId: undefined as number | undefined,
        ruleCode: "",
        ruleName: "",
        ruleType: "VALIDATION" as ArchiveRuleType,
        triggerCode: "",
        scopeFondsCode: "",
        scopeCategoryCode: "",
        scopeArchiveLevel: undefined as ArchiveLevel | undefined,
        priority: 0,
        conditionJson: '{"field":"fixed.archiveYear","operator":"GTE","value":2020}',
        effectType: "VALIDATION_ERROR" as ArchiveRuleEffectType,
        effectParams: '{"message":"规则命中"}',
        enabled: true,
    };
}

function defaultExecuteForm() {
    return {
        schemeVersionId: schemeVersionId.value,
        triggerCode: "BEFORE_SAVE",
        fondsCode: "",
        categoryCode: "",
        objectTypeCode: "ARCHIVE_ITEM",
        archiveLevel: "ITEM" as ArchiveLevel,
        facts: '{"fixed.archiveYear":2026}',
        includeSkipped: false,
        recordTrace: false,
    };
}

async function loadRules() {
    if (schemeVersionId.value == null) {
        rules.value = [];
        return;
    }
    loading.value = true;
    try {
        rules.value = (await listArchiveRules(schemeVersionId.value, status.value)).items;
    } catch (error) {
        ElMessage.error((error as Error).message);
    } finally {
        loading.value = false;
    }
}

watch([schemeVersionId, status], () => void loadRules());
onMounted(() => void loadRules());

function openRuleModal() {
    ruleForm.value = { ...defaultRuleForm(), schemeVersionId: schemeVersionId.value };
    ruleModalOpen.value = true;
}

function openExecuteModal() {
    executeForm.value = defaultExecuteForm();
    executeModalOpen.value = true;
}

async function submitRule() {
    if (!(await ruleFormRef.value?.validate().catch(() => false))) return;
    ruleSubmitting.value = true;
    try {
        const values = ruleForm.value;
        await createArchiveRule({
            schemeVersionId: values.schemeVersionId!,
            ruleCode: values.ruleCode,
            ruleName: values.ruleName,
            ruleType: values.ruleType,
            triggerCode: values.triggerCode,
            scopeFondsCode: values.scopeFondsCode || undefined,
            scopeCategoryCode: values.scopeCategoryCode || undefined,
            scopeArchiveLevel: values.scopeArchiveLevel,
            priority: values.priority,
            conditionJson: parseJson(values.conditionJson),
            enabled: values.enabled,
            effects: [
                {
                    effectType: values.effectType,
                    effectOrder: 0,
                    effectParams: parseJson(values.effectParams || "{}"),
                },
            ],
        });
        ElMessage.success("规则已创建");
        ruleModalOpen.value = false;
        await loadRules();
    } catch (error) {
        ElMessage.error((error as Error).message);
    } finally {
        ruleSubmitting.value = false;
    }
}

async function publishRule(id: number) {
    try {
        await publishArchiveRule(id);
        ElMessage.success("规则已发布");
        await loadRules();
    } catch (error) {
        ElMessage.error((error as Error).message);
    }
}

async function changeEnabled(value: unknown, enabled: boolean) {
    const row = value as ArchiveRuleDto;
    try {
        await (enabled ? enableArchiveRule(row.id) : disableArchiveRule(row.id));
        await loadRules();
    } catch (error) {
        ElMessage.error((error as Error).message);
        await loadRules();
    }
}

async function submitExecute() {
    if (!(await executeFormRef.value?.validate().catch(() => false))) return;
    executeSubmitting.value = true;
    try {
        const values = executeForm.value;
        const response = await executeArchiveRules({
            schemeVersionId: values.schemeVersionId!,
            triggerCode: values.triggerCode,
            fondsCode: values.fondsCode || undefined,
            categoryCode: values.categoryCode || undefined,
            objectTypeCode: values.objectTypeCode || undefined,
            archiveLevel: values.archiveLevel,
            facts: parseJson(values.facts),
            includeSkipped: values.includeSkipped,
            recordTrace: values.recordTrace,
        });
        decisions.value = response.items;
        ElMessage.success("规则试算完成");
    } catch (error) {
        ElMessage.error((error as Error).message);
    } finally {
        executeSubmitting.value = false;
    }
}

function parseJson(value: string) {
    try {
        return JSON.parse(value || "{}") as Record<string, unknown>;
    } catch {
        throw new Error("JSON 格式不正确");
    }
}
</script>

<template>
    <section class="am-page">
        <div class="am-page__header">
            <h1>本地规则</h1>
            <div class="am-page__actions">
                <el-input-number
                    v-model="schemeVersionId"
                    :min="1"
                    placeholder="治理版本 ID"
                    controls-position="right"
                />
                <el-select v-model="status" clearable placeholder="状态" style="width: 120px">
                    <el-option label="草稿" value="DRAFT" /><el-option
                        label="已发布"
                        value="PUBLISHED"
                    />
                </el-select>
                <el-button type="primary" @click="openRuleModal">新建规则</el-button>
                <el-button @click="openExecuteModal">规则试算</el-button>
            </div>
        </div>
        <el-card shadow="never">
            <el-table v-loading="loading" :data="rules" row-key="id">
                <el-table-column prop="ruleCode" label="编码" width="180" />
                <el-table-column prop="ruleName" label="名称" />
                <el-table-column prop="ruleType" label="类型" width="130" />
                <el-table-column prop="triggerCode" label="触发点" width="130" />
                <el-table-column prop="priority" label="优先级" width="90" />
                <el-table-column label="状态" width="100"
                    ><template #default="{ row }"
                        ><el-tag :type="row.status === 'PUBLISHED' ? 'primary' : 'info'">{{
                            row.status === "PUBLISHED" ? "已发布" : "草稿"
                        }}</el-tag></template
                    ></el-table-column
                >
                <el-table-column label="启用" width="90"
                    ><template #default="{ row }"
                        ><el-switch
                            :model-value="row.enabled"
                            @change="changeEnabled(row, Boolean($event))" /></template
                ></el-table-column>
                <el-table-column label="操作" width="110"
                    ><template #default="{ row }"
                        ><el-button
                            size="small"
                            :disabled="row.status !== 'DRAFT'"
                            @click="publishRule(row.id)"
                            >发布</el-button
                        ></template
                    ></el-table-column
                >
            </el-table>
        </el-card>

        <el-dialog v-model="ruleModalOpen" title="新建规则" width="720px" destroy-on-close>
            <el-form ref="ruleFormRef" :model="ruleForm" label-position="top">
                <el-form-item
                    label="治理版本 ID"
                    prop="schemeVersionId"
                    :rules="[{ required: true, message: '请输入治理版本 ID' }]"
                    ><el-input-number
                        v-model="ruleForm.schemeVersionId"
                        :min="1"
                        controls-position="right"
                /></el-form-item>
                <el-form-item
                    label="规则编码"
                    prop="ruleCode"
                    :rules="[{ required: true, message: '请输入规则编码' }]"
                    ><el-input v-model="ruleForm.ruleCode"
                /></el-form-item>
                <el-form-item
                    label="规则名称"
                    prop="ruleName"
                    :rules="[{ required: true, message: '请输入规则名称' }]"
                    ><el-input v-model="ruleForm.ruleName"
                /></el-form-item>
                <el-form-item label="规则类型"
                    ><el-select v-model="ruleForm.ruleType"
                        ><el-option
                            v-for="value in ruleTypes"
                            :key="value"
                            :label="value"
                            :value="value" /></el-select
                ></el-form-item>
                <el-form-item
                    label="触发点"
                    prop="triggerCode"
                    :rules="[{ required: true, message: '请输入触发点' }]"
                    ><el-input v-model="ruleForm.triggerCode" placeholder="BEFORE_SAVE"
                /></el-form-item>
                <el-form-item label="优先级"
                    ><el-input-number v-model="ruleForm.priority" controls-position="right"
                /></el-form-item>
                <el-form-item
                    label="条件树 JSON"
                    prop="conditionJson"
                    :rules="[{ required: true, message: '请输入条件树 JSON' }]"
                    ><el-input v-model="ruleForm.conditionJson" type="textarea" :rows="5"
                /></el-form-item>
                <el-form-item label="effect 类型"
                    ><el-select v-model="ruleForm.effectType"
                        ><el-option
                            v-for="value in effectTypes"
                            :key="value"
                            :label="value"
                            :value="value" /></el-select
                ></el-form-item>
                <el-form-item label="effect 参数 JSON"
                    ><el-input v-model="ruleForm.effectParams" type="textarea" :rows="3"
                /></el-form-item>
                <el-form-item label="启用"><el-switch v-model="ruleForm.enabled" /></el-form-item>
            </el-form>
            <template #footer
                ><el-button @click="ruleModalOpen = false">取消</el-button
                ><el-button type="primary" :loading="ruleSubmitting" @click="submitRule"
                    >确定</el-button
                ></template
            >
        </el-dialog>

        <el-dialog v-model="executeModalOpen" title="规则试算" width="760px" destroy-on-close>
            <el-form ref="executeFormRef" :model="executeForm" label-position="top">
                <el-form-item
                    label="治理版本 ID"
                    prop="schemeVersionId"
                    :rules="[{ required: true, message: '请输入治理版本 ID' }]"
                    ><el-input-number
                        v-model="executeForm.schemeVersionId"
                        :min="1"
                        controls-position="right"
                /></el-form-item>
                <el-form-item
                    label="触发点"
                    prop="triggerCode"
                    :rules="[{ required: true, message: '请输入触发点' }]"
                    ><el-input v-model="executeForm.triggerCode"
                /></el-form-item>
                <el-form-item label="对象类型"
                    ><el-input v-model="executeForm.objectTypeCode"
                /></el-form-item>
                <el-form-item label="对象层级"
                    ><el-select v-model="executeForm.archiveLevel"
                        ><el-option label="条目" value="ITEM" /><el-option
                            label="案卷"
                            value="VOLUME" /></el-select
                ></el-form-item>
                <el-form-item
                    label="事实 JSON"
                    prop="facts"
                    :rules="[{ required: true, message: '请输入事实 JSON' }]"
                    ><el-input v-model="executeForm.facts" type="textarea" :rows="5"
                /></el-form-item>
                <el-form-item label="返回未命中"
                    ><el-switch v-model="executeForm.includeSkipped"
                /></el-form-item>
                <el-form-item label="保存追踪"
                    ><el-switch v-model="executeForm.recordTrace"
                /></el-form-item>
            </el-form>
            <el-table :data="decisions" size="small">
                <el-table-column prop="ruleCode" label="规则" /><el-table-column
                    label="命中"
                    width="80"
                    ><template #default="{ row }">{{
                        row.matched ? "是" : "否"
                    }}</template></el-table-column
                >
                <el-table-column prop="severity" label="级别" width="90" /><el-table-column
                    label="阻断"
                    width="80"
                    ><template #default="{ row }">{{
                        row.blocking ? "是" : "否"
                    }}</template></el-table-column
                ><el-table-column prop="message" label="消息" />
            </el-table>
            <template #footer
                ><el-button @click="executeModalOpen = false">取消</el-button
                ><el-button type="primary" :loading="executeSubmitting" @click="submitExecute"
                    >确定</el-button
                ></template
            >
        </el-dialog>
    </section>
</template>
