// web/src/pages/login-sessions/LoginSessionsPage.tsx
import { deleteLoginSession, listLoginSessions } from "@archive-management/frontend-core/api";
import type { LoginSessionDto } from "@archive-management/frontend-core/types";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button, Card, Popconfirm, Space, Table, Tag, Typography, message } from "antd";
import type { TableColumnsType } from "antd";
import { useState } from "react";

import { CursorPagination } from "@/shared/components/CursorPagination";

const loginSessionsQueryKey = ["login-sessions"] as const;

export function LoginSessionsPage() {
    const queryClient = useQueryClient();
    const [messageApi, contextHolder] = message.useMessage();
    const [limit, setLimit] = useState(100);
    const [cursor, setCursor] = useState<string | null>(null);
    const sessionsQuery = useQuery({
        queryKey: [...loginSessionsQueryKey, limit, cursor],
        queryFn: () =>
            listLoginSessions({
                limit,
                cursor,
                requestTotal: !cursor,
            }),
    });
    const deleteMutation = useMutation({
        mutationFn: (sessionId: string) => deleteLoginSession(sessionId),
        onSuccess: async () => {
            await queryClient.invalidateQueries({ queryKey: loginSessionsQueryKey });
            messageApi.success("登录会话已踢下线");
        },
    });

    const columns: TableColumnsType<LoginSessionDto> = [
        {
            title: "用户",
            dataIndex: "displayName",
            key: "displayName",
            width: 180,
            render: (_value, row) => (
                <Space size={6}>
                    <span>{row.displayName || row.username}</span>
                    {row.current ? <Tag color="blue">当前</Tag> : null}
                </Space>
            ),
        },
        { title: "账号", dataIndex: "username", key: "username", width: 160 },
        {
            title: "客户端",
            key: "client",
            width: 260,
            render: (_value, row) => (
                <Space direction="vertical" size={0}>
                    <span>{clientSummary(row)}</span>
                    <Typography.Text type="secondary">
                        {row.client.userAgent || "-"}
                    </Typography.Text>
                </Space>
            ),
        },
        {
            title: "请求",
            key: "request",
            width: 220,
            render: (_value, row) => (
                <Space direction="vertical" size={0}>
                    <span>{row.request.remoteAddress || "-"}</span>
                    <Typography.Text type="secondary">{row.request.host || "-"}</Typography.Text>
                </Space>
            ),
        },
        {
            title: "最后访问",
            dataIndex: "lastAccessTime",
            key: "lastAccessTime",
            width: 180,
            render: formatDateTime,
        },
        {
            title: "过期时间",
            dataIndex: "expiresAt",
            key: "expiresAt",
            width: 180,
            render: formatDateTime,
        },
        {
            title: "操作",
            key: "actions",
            fixed: "right",
            width: 110,
            render: (_value, row) =>
                row.current ? (
                    <Button disabled size="small">
                        当前会话
                    </Button>
                ) : (
                    <Popconfirm
                        title="踢下线该登录会话？"
                        okButtonProps={{ danger: true }}
                        okText="踢下线"
                        cancelText="取消"
                        onConfirm={() => deleteMutation.mutate(row.sessionId)}
                    >
                        <Button
                            danger
                            loading={deleteMutation.variables === row.sessionId}
                            size="small"
                        >
                            踢下线
                        </Button>
                    </Popconfirm>
                ),
        },
    ];

    return (
        <section className="am-page">
            {contextHolder}
            <div className="am-page__header">
                <Typography.Title level={1}>登录会话</Typography.Title>
                <Typography.Text type="secondary">
                    {sessionsQuery.data?.total !== undefined && sessionsQuery.data.total !== null
                        ? `共 ${sessionsQuery.data.total} 条`
                        : ""}
                </Typography.Text>
            </div>
            <Card>
                <Table<LoginSessionDto>
                    columns={columns}
                    dataSource={sessionsQuery.data?.items ?? []}
                    loading={sessionsQuery.isLoading}
                    pagination={false}
                    rowKey="sessionId"
                    scroll={{ x: 1180 }}
                />
                <div className="am-table-footer">
                    <CursorPagination
                        limit={limit}
                        loading={sessionsQuery.isFetching}
                        next={sessionsQuery.data?.next}
                        prev={sessionsQuery.data?.prev}
                        onLimitChange={(value) => {
                            setLimit(value);
                            setCursor(null);
                        }}
                        onPage={setCursor}
                    />
                </div>
            </Card>
        </section>
    );
}

function clientSummary(row: LoginSessionDto) {
    return (
        [row.client.browserName, row.client.osName, row.client.deviceType]
            .filter(Boolean)
            .join(" / ") || "-"
    );
}

function formatDateTime(value?: string | null) {
    return value ? value.replace("T", " ") : "-";
}

// web/src/pages/login-sessions/LoginSessionsPage.vue
<script setup lang="ts">
import { deleteLoginSession, listLoginSessions } from "@archive-management/frontend-core/api";
import type { LoginSessionDto } from "@archive-management/frontend-core/types";
import { ElMessage, ElMessageBox } from "element-plus";
import { onMounted, ref } from "vue";

import CursorPagination from "@/shared/components/CursorPagination.vue";

const limit = ref(100);
const cursor = ref<string | null>(null);
const sessions = ref<LoginSessionDto[]>([]);
const total = ref<number | null>();
const prev = ref<string | null>();
const next = ref<string | null>();
const loading = ref(false);
const deletingId = ref<string>();

async function loadSessions() {
    loading.value = true;
    try {
        const response = await listLoginSessions({
            limit: limit.value,
            cursor: cursor.value,
            requestTotal: !cursor.value,
        });
        sessions.value = response.items;
        prev.value = response.prev;
        next.value = response.next;
        if (!cursor.value) total.value = response.total;
    } finally {
        loading.value = false;
    }
}

async function kickout(value: unknown) {
    const row = value as LoginSessionDto;
    try {
        await ElMessageBox.confirm("踢下线该登录会话？", "确认操作", {
            confirmButtonText: "踢下线",
            cancelButtonText: "取消",
            confirmButtonClass: "el-button--danger",
            type: "warning",
        });
    } catch {
        return;
    }
    deletingId.value = row.sessionId;
    try {
        await deleteLoginSession(row.sessionId);
        await loadSessions();
        ElMessage.success("登录会话已踢下线");
    } finally {
        deletingId.value = undefined;
    }
}

function changeLimit(value: number) {
    limit.value = value;
    cursor.value = null;
    void loadSessions();
}

function changePage(value: string) {
    cursor.value = value;
    void loadSessions();
}

function clientSummary(value: unknown) {
    const row = value as LoginSessionDto;
    return (
        [row.client.browserName, row.client.osName, row.client.deviceType]
            .filter(Boolean)
            .join(" / ") || "-"
    );
}

function formatDateTime(value?: string | null) {
    return value ? value.replace("T", " ") : "-";
}

onMounted(loadSessions);
</script>

<template>
    <section class="am-page">
        <div class="am-page__header">
            <h1>登录会话</h1>
            <el-text type="info">{{ total == null ? "" : `共 ${total} 条` }}</el-text>
        </div>
        <el-card shadow="never">
            <el-table v-loading="loading" :data="sessions" row-key="sessionId">
                <el-table-column label="用户" width="180">
                    <template #default="{ row }">
                        <div class="cell-inline">
                            <span>{{ row.displayName || "-" }}</span
                            ><el-tag v-if="row.current" type="primary">当前</el-tag>
                        </div>
                    </template>
                </el-table-column>
                <el-table-column label="账号" prop="username" width="160" />
                <el-table-column label="客户端" width="260">
                    <template #default="{ row }"
                        ><div>{{ clientSummary(row) }}</div>
                        <el-text type="info">{{ row.client.userAgent || "-" }}</el-text></template
                    >
                </el-table-column>
                <el-table-column label="请求" width="220">
                    <template #default="{ row }"
                        ><div>{{ row.request.remoteAddress || "-" }}</div>
                        <el-text type="info">{{ row.request.host || "-" }}</el-text></template
                    >
                </el-table-column>
                <el-table-column label="最后访问" width="180"
                    ><template #default="{ row }">{{
                        formatDateTime(row.lastAccessTime)
                    }}</template></el-table-column
                >
                <el-table-column label="过期时间" width="180"
                    ><template #default="{ row }">{{
                        formatDateTime(row.expiresAt)
                    }}</template></el-table-column
                >
                <el-table-column fixed="right" label="操作" width="110">
                    <template #default="{ row }">
                        <el-button v-if="row.current" disabled size="small">当前会话</el-button>
                        <el-button
                            v-else
                            type="danger"
                            plain
                            size="small"
                            :loading="deletingId === row.sessionId"
                            @click="kickout(row)"
                            >踢下线</el-button
                        >
                    </template>
                </el-table-column>
            </el-table>
            <div class="am-table-footer">
                <CursorPagination
                    :limit="limit"
                    :loading="loading"
                    :next="next"
                    :prev="prev"
                    @limit-change="changeLimit"
                    @page="changePage"
                />
            </div>
        </el-card>
    </section>
</template>

<style scoped>
.cell-inline {
    display: flex;
    align-items: center;
    gap: 6px;
}
</style>
