// frontend/admin/src/pages/login/LoginPage.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, reactive, ref } from "vue";
import { useRouter } from "vue-router";
import type { CapWidget } from "cap-widget";

import { errorMessage } from "@archive-management/frontend-core/api";
import {
    capWidgetApiEndpoint,
    createCapVerificationController,
} from "@archive-management/frontend-core/cap";

import { usePageTabsStore } from "@/stores/pageTabsStore";
import { usePermissionStore } from "@/stores/permissionStore";
import { useSessionStore } from "@/stores/sessionStore";

const props = withDefaults(defineProps<{ redirect?: string }>(), { redirect: "/" });
const router = useRouter();
const sessionStore = useSessionStore();
const permissionStore = usePermissionStore();
const pageTabsStore = usePageTabsStore();
const form = reactive({ username: "", password: "" });
const capWidget = ref<CapWidget | null>(null);
const powToken = ref("");
const securityMessage = ref("请完成安全验证");
const submitting = ref(false);
const loginError = ref("");
const controller = createCapVerificationController(() => capWidget.value);
const unsubscribe = controller.subscribe((state) => {
    powToken.value = state.powToken;
    securityMessage.value = state.securityMessage;
});

async function submitLogin() {
    const username = form.username.trim();
    if (!username || !form.password) {
        loginError.value = "请输入账号和密码";
        return;
    }
    if (!powToken.value) {
        loginError.value = "请先完成安全验证";
        return;
    }

    submitting.value = true;
    loginError.value = "";
    try {
        await sessionStore.loginWithPassword({
            username,
            password: form.password,
            powToken: powToken.value,
        });
        pageTabsStore.reset();
        await permissionStore.fetchSummary().catch(() => undefined);
        await router.replace(props.redirect);
    } catch (error) {
        loginError.value = errorMessage(error, "登录失败");
        controller.reset("请重新完成安全验证");
    } finally {
        submitting.value = false;
    }
}

onMounted(() => {
    if (sessionStore.currentUser) {
        void router.replace(props.redirect);
        return;
    }
    capWidget.value?.addEventListener("solve", controller.handleSolve);
    capWidget.value?.addEventListener("reset", controller.handleReset);
    capWidget.value?.addEventListener("error", controller.handleError);
});

onBeforeUnmount(() => {
    capWidget.value?.removeEventListener("solve", controller.handleSolve);
    capWidget.value?.removeEventListener("reset", controller.handleReset);
    capWidget.value?.removeEventListener("error", controller.handleError);
    unsubscribe();
});
</script>

<template>
    <main class="am-login">
        <ElCard class="am-login__panel" shadow="never">
            <h1>账号登录</h1>
            <p class="am-text-secondary">进入档案业务工作台</p>
            <ElForm label-position="top" @submit.prevent="submitLogin">
                <ElFormItem label="账号"
                    ><ElInput v-model="form.username" autocomplete="username"
                /></ElFormItem>
                <ElFormItem label="密码"
                    ><ElInput
                        v-model="form.password"
                        autocomplete="current-password"
                        show-password
                        type="password"
                        @keyup.enter="submitLogin"
                /></ElFormItem>
                <div class="am-login__pow">
                    <cap-widget
                        ref="capWidget"
                        :data-cap-api-endpoint="capWidgetApiEndpoint()"
                        data-cap-hidden-field-name="powToken"
                        data-cap-i18n-error-aria-label="安全验证失败"
                        data-cap-i18n-error-label="验证失败"
                        data-cap-i18n-initial-state="点击完成安全验证"
                        data-cap-i18n-solved-label="安全验证已完成"
                        data-cap-i18n-verified-aria-label="安全验证已完成"
                        data-cap-i18n-verifying-aria-label="正在完成安全验证"
                        data-cap-i18n-verifying-label="正在验证..."
                        data-cap-i18n-verify-aria-label="完成安全验证"
                        data-cap-worker-count="2"
                        data-testid="cap-widget"
                        required
                    />
                    <span :class="powToken ? 'am-text-success' : 'am-text-secondary'">{{
                        securityMessage
                    }}</span>
                </div>
                <p v-if="loginError" class="am-form-error" role="alert">{{ loginError }}</p>
                <ElButton
                    :loading="submitting"
                    native-type="submit"
                    type="primary"
                    class="am-login__submit"
                    >登录系统</ElButton
                >
            </ElForm>
        </ElCard>
    </main>
</template>

// web/src/pages/login/LoginPage.tsx
import { Button, Card, Form, Input, Typography } from "antd";
import { errorMessage } from "@archive-management/frontend-core/api";
import { capWidgetApiEndpoint, useCapVerification } from "@archive-management/frontend-core/cap";
import { useSessionStore } from "@archive-management/frontend-core/auth";
import { createElement, forwardRef, useEffect, useRef, useState } from "react";
import type { HTMLAttributes } from "react";
import { useLocation, useNavigate } from "react-router";
import type { CapWidget } from "cap-widget";

interface LoginFormValues {
    username: string;
    password: string;
}

export function LoginPage() {
    const [form] = Form.useForm<LoginFormValues>();
    const location = useLocation();
    const navigate = useNavigate();
    const capWidgetRef = useRef<CapWidget | null>(null);
    const [submitting, setSubmitting] = useState(false);
    const [loginError, setLoginError] = useState("");
    const loginWithPassword = useSessionStore((state) => state.loginWithPassword);
    const currentUser = useSessionStore((state) => state.currentUser);
    const {
        powToken,
        securityMessage,
        resetCapWidget,
        handleCapSolve,
        handleCapReset,
        handleCapError,
    } = useCapVerification(capWidgetRef);

    useEffect(() => {
        const widget = capWidgetRef.current;
        if (!widget) {
            return undefined;
        }
        widget.addEventListener("solve", handleCapSolve);
        widget.addEventListener("reset", handleCapReset);
        widget.addEventListener("error", handleCapError);
        return () => {
            widget.removeEventListener("solve", handleCapSolve);
            widget.removeEventListener("reset", handleCapReset);
            widget.removeEventListener("error", handleCapError);
        };
    }, [handleCapError, handleCapReset, handleCapSolve]);

    useEffect(() => {
        if (currentUser) {
            void navigate(redirectTarget(location.search), { replace: true });
        }
    }, [currentUser, location.search, navigate]);

    async function submitLogin(values: LoginFormValues) {
        const username = values.username?.trim();
        const password = values.password;
        if (!username || !password) {
            setLoginError("请输入账号和密码");
            return;
        }
        if (!powToken) {
            setLoginError("请先完成安全验证");
            return;
        }

        setSubmitting(true);
        setLoginError("");
        try {
            await loginWithPassword({ username, password, powToken });
            await navigate(redirectTarget(location.search), { replace: true });
        } catch (error) {
            setLoginError(errorMessage(error, "登录失败"));
            resetCapWidget("请重新完成安全验证");
        } finally {
            setSubmitting(false);
        }
    }

    return (
        <main className="am-login">
            <Card className="am-login__panel">
                <Typography.Title level={1}>账号登录</Typography.Title>
                <Typography.Paragraph type="secondary">进入档案业务工作台</Typography.Paragraph>
                <Form form={form} layout="vertical" onFinish={(values) => void submitLogin(values)}>
                    <Form.Item label="账号" name="username">
                        <Input autoComplete="username" />
                    </Form.Item>
                    <Form.Item label="密码" name="password">
                        <Input.Password
                            autoComplete="current-password"
                            onPressEnter={form.submit}
                        />
                    </Form.Item>
                    <div className="am-login__pow">
                        <CapWidgetElement
                            ref={capWidgetRef}
                            data-cap-api-endpoint={capWidgetApiEndpoint()}
                            data-cap-hidden-field-name="powToken"
                            data-cap-i18n-error-aria-label="安全验证失败"
                            data-cap-i18n-error-label="验证失败"
                            data-cap-i18n-initial-state="点击完成安全验证"
                            data-cap-i18n-solved-label="安全验证已完成"
                            data-cap-i18n-verified-aria-label="安全验证已完成"
                            data-cap-i18n-verifying-aria-label="正在完成安全验证"
                            data-cap-i18n-verifying-label="正在验证..."
                            data-cap-i18n-verify-aria-label="完成安全验证"
                            data-cap-worker-count="2"
                            data-testid="cap-widget"
                            required
                        />
                        <Typography.Text type={powToken ? "success" : "secondary"}>
                            {securityMessage}
                        </Typography.Text>
                    </div>
                    {loginError ? (
                        <Typography.Text type="danger">{loginError}</Typography.Text>
                    ) : null}
                    <Button block htmlType="submit" loading={submitting} type="primary">
                        登录系统
                    </Button>
                </Form>
            </Card>
        </main>
    );
}

type CapWidgetElementProps = HTMLAttributes<HTMLElement> & {
    "data-cap-api-endpoint": string;
    "data-cap-hidden-field-name": string;
    "data-cap-worker-count": string;
    "data-cap-i18n-initial-state": string;
    "data-cap-i18n-verifying-label": string;
    "data-cap-i18n-solved-label": string;
    "data-cap-i18n-error-label": string;
    "data-cap-i18n-verify-aria-label": string;
    "data-cap-i18n-verifying-aria-label": string;
    "data-cap-i18n-verified-aria-label": string;
    "data-cap-i18n-error-aria-label": string;
    required?: boolean;
};

const CapWidgetElement = forwardRef<CapWidget, CapWidgetElementProps>((props, ref) =>
    createElement("cap-widget", { ...props, ref }),
);

function redirectTarget(search: string) {
    const redirect = new URLSearchParams(search).get("redirect");
    if (!redirect || !redirect.startsWith("/") || redirect.startsWith("//")) {
        return "/";
    }
    return redirect;
}
