// frontend/admin/src/pages/authentication-events/AuthenticationEventsPage.vue
<script setup lang="ts">
import { listAuthenticationEvents } from "@archive-management/frontend-core/api";
import type {
    AuthenticationEventDto,
    ListAuthenticationEventsParams,
} from "@archive-management/frontend-core/types";
import { Search } from "@element-plus/icons-vue";
import { onMounted, reactive, ref } from "vue";

import CursorPagination from "@/shared/components/CursorPagination.vue";
import { AmDataTable } from "@/shared/components/data-table";

const eventTypeOptions = [
    { label: "登录成功", value: "login_success" },
    { label: "登录失败", value: "login_failure" },
    { label: "主动退出", value: "logout" },
    { label: "踢下线", value: "kickout" },
];

const form = reactive<{
    eventType?: string;
    username: string;
    keyword: string;
    occurredRange?: [string, string];
}>({ username: "", keyword: "" });
const filters = ref<ListAuthenticationEventsParams>({});
const limit = ref(100);
const cursor = ref<string | null>(null);
const events = ref<AuthenticationEventDto[]>([]);
const total = ref<number | null>();
const prev = ref<string | null>();
const next = ref<string | null>();
const loading = ref(false);

async function loadEvents() {
    loading.value = true;
    try {
        const response = await listAuthenticationEvents({
            ...filters.value,
            limit: limit.value,
            cursor: cursor.value,
            requestTotal: !cursor.value,
        });
        events.value = response.items;
        prev.value = response.prev;
        next.value = response.next;
        if (!cursor.value) total.value = response.total;
    } finally {
        loading.value = false;
    }
}

function search() {
    filters.value = {
        eventType: form.eventType,
        username: form.username.trim() || undefined,
        keyword: form.keyword.trim() || undefined,
        occurredAfter: form.occurredRange?.[0],
        occurredBefore: form.occurredRange?.[1],
    };
    cursor.value = null;
    void loadEvents();
}

function reset() {
    form.eventType = undefined;
    form.username = "";
    form.keyword = "";
    form.occurredRange = undefined;
    filters.value = {};
    cursor.value = null;
    void loadEvents();
}

function changeLimit(value: number) {
    limit.value = value;
    cursor.value = null;
    void loadEvents();
}
function changePage(value: string) {
    cursor.value = value;
    void loadEvents();
}
function eventLabel(type: string) {
    return eventTypeOptions.find((option) => option.value === type)?.label ?? type;
}
function eventTagType(type: string) {
    return type === "login_success"
        ? "success"
        : type === "login_failure"
          ? "danger"
          : type === "kickout"
            ? "warning"
            : "info";
}
function clientSummary(value: unknown) {
    const row = value as AuthenticationEventDto;
    return (
        [row.client.browserName, row.client.osName, row.client.deviceType]
            .filter(Boolean)
            .join(" / ") || "-"
    );
}
function formatDateTime(value?: string | null) {
    return value ? value.replace("T", " ") : "-";
}

onMounted(loadEvents);
</script>

<template>
    <section class="am-page">
        <div class="am-page__header">
            <h1>认证审计</h1>
            <el-text type="info">{{ total == null ? "" : `共 ${total} 条` }}</el-text>
        </div>
        <el-card class="am-page__filter" shadow="never">
            <el-form :inline="true" :model="form" @submit.prevent="search">
                <el-form-item
                    ><el-select
                        v-model="form.eventType"
                        clearable
                        placeholder="事件类型"
                        style="width: 140px"
                        ><el-option
                            v-for="option in eventTypeOptions"
                            :key="option.value"
                            :label="option.label"
                            :value="option.value" /></el-select
                ></el-form-item>
                <el-form-item
                    ><el-input
                        v-model="form.username"
                        clearable
                        placeholder="账号"
                        style="width: 160px"
                /></el-form-item>
                <el-form-item
                    ><el-input
                        v-model="form.keyword"
                        clearable
                        placeholder="关键字"
                        style="width: 220px"
                /></el-form-item>
                <el-form-item
                    ><el-date-picker
                        v-model="form.occurredRange"
                        type="datetimerange"
                        value-format="YYYY-MM-DDTHH:mm:ss"
                        start-placeholder="开始时间"
                        end-placeholder="结束时间"
                /></el-form-item>
                <el-form-item
                    ><el-button native-type="submit" type="primary" :icon="Search">查询</el-button
                    ><el-button @click="reset">重置</el-button></el-form-item
                >
            </el-form>
        </el-card>
        <el-card class="am-page__result" shadow="never">
            <AmDataTable
                :data="events"
                :loading="loading"
                row-key="id"
                sort-mode="none"
                :columns="[
                    { key: 'eventType', label: '事件', width: 120 },
                    { key: 'username', label: '账号', width: 150 },
                    { key: 'displayName', label: '用户', width: 160 },
                    { key: 'operatorUsername', label: '操作人', width: 140 },
                    { key: 'client', label: '客户端', width: 240 },
                    { key: 'request', label: '请求', width: 220 },
                    { key: 'failureReason', label: '失败原因', width: 220 },
                    { key: 'occurredAt', label: '发生时间', width: 180 },
                ]"
            >
                <template #cell-eventType="{ row }">
                    <el-tag :type="eventTagType(row.eventType)">{{
                        eventLabel(row.eventType)
                    }}</el-tag>
                </template>
                <template #cell-operatorUsername="{ row }">{{
                    row.operatorUsername || "-"
                }}</template>
                <template #cell-client="{ row }">
                    <div>{{ clientSummary(row) }}</div>
                    <el-text type="info">{{ row.client.userAgent || "-" }}</el-text>
                </template>
                <template #cell-request="{ row }">
                    <div>{{ row.request.remoteAddress || "-" }}</div>
                    <el-text type="info">{{ row.request.host || "-" }}</el-text>
                </template>
                <template #cell-failureReason="{ row }">{{ row.failureReason || "-" }}</template>
                <template #cell-occurredAt="{ row }">
                    {{ formatDateTime(row.occurredAt) }}
                </template>
            </AmDataTable>
            <div class="am-table-footer">
                <CursorPagination
                    :limit="limit"
                    :total="total ?? undefined"
                    :loading="loading"
                    :next="next"
                    :prev="prev"
                    @limit-change="changeLimit"
                    @page="changePage"
                />
            </div>
        </el-card>
    </section>
</template>

// web/src/pages/authentication-events/AuthenticationEventsPage.tsx
import { listAuthenticationEvents } from "@archive-management/frontend-core/api";
import type {
    AuthenticationEventDto,
    ListAuthenticationEventsParams,
} from "@archive-management/frontend-core/types";
import { SearchOutlined } from "@ant-design/icons";
import { useQuery } from "@tanstack/react-query";
import { Button, Card, DatePicker, Form, Input, Select, Space, Table, Tag, Typography } from "antd";
import type { TableColumnsType } from "antd";
import type { Dayjs } from "dayjs";
import { useState } from "react";

import { CursorPagination } from "@/shared/components/CursorPagination";

const { RangePicker } = DatePicker;

const eventTypeOptions = [
    { label: "登录成功", value: "login_success" },
    { label: "登录失败", value: "login_failure" },
    { label: "主动退出", value: "logout" },
    { label: "踢下线", value: "kickout" },
];

export function AuthenticationEventsPage() {
    const [limit, setLimit] = useState(100);
    const [cursor, setCursor] = useState<string | null>(null);
    const [filters, setFilters] = useState<ListAuthenticationEventsParams>({});
    const eventsQuery = useQuery({
        queryKey: ["authentication-events", limit, cursor, filters],
        queryFn: () =>
            listAuthenticationEvents({
                ...filters,
                limit,
                cursor,
                requestTotal: !cursor,
            }),
    });

    const columns: TableColumnsType<AuthenticationEventDto> = [
        {
            title: "事件",
            dataIndex: "eventType",
            key: "eventType",
            width: 120,
            render: (eventType: string) => (
                <Tag color={eventColor(eventType)}>{eventLabel(eventType)}</Tag>
            ),
        },
        { title: "账号", dataIndex: "username", key: "username", width: 150 },
        { title: "用户", dataIndex: "displayName", key: "displayName", width: 160 },
        {
            title: "操作人",
            dataIndex: "operatorUsername",
            key: "operatorUsername",
            width: 140,
            render: (value: string) => value || "-",
        },
        {
            title: "客户端",
            key: "client",
            width: 240,
            render: (_value, row) => (
                <Space orientation="vertical" size={0}>
                    <span>{clientSummary(row)}</span>
                    <Typography.Text type="secondary">
                        {row.client.userAgent || "-"}
                    </Typography.Text>
                </Space>
            ),
        },
        {
            title: "请求",
            key: "request",
            width: 220,
            render: (_value, row) => (
                <Space orientation="vertical" size={0}>
                    <span>{row.request.remoteAddress || "-"}</span>
                    <Typography.Text type="secondary">{row.request.host || "-"}</Typography.Text>
                </Space>
            ),
        },
        {
            title: "失败原因",
            dataIndex: "failureReason",
            key: "failureReason",
            width: 220,
            render: (value: string) => value || "-",
        },
        {
            title: "发生时间",
            dataIndex: "occurredAt",
            key: "occurredAt",
            width: 180,
            render: formatDateTime,
        },
    ];

    return (
        <section className="am-page">
            <div className="am-page__header">
                <Typography.Title level={1}>认证审计</Typography.Title>
                <Typography.Text type="secondary">
                    {eventsQuery.data?.total !== undefined && eventsQuery.data.total !== null
                        ? `共 ${eventsQuery.data.total} 条`
                        : ""}
                </Typography.Text>
            </div>
            <Card className="am-page__filter">
                <AuthenticationEventFilter
                    onSearch={(nextFilters) => {
                        setFilters(nextFilters);
                        setCursor(null);
                    }}
                />
            </Card>
            <Card className="am-page__result">
                <Table<AuthenticationEventDto>
                    columns={columns}
                    dataSource={eventsQuery.data?.items ?? []}
                    loading={eventsQuery.isLoading}
                    pagination={false}
                    rowKey={(row) => String(row.id)}
                    scroll={{ x: 1410 }}
                />
                <div className="am-table-footer">
                    <CursorPagination
                        limit={limit}
                        loading={eventsQuery.isFetching}
                        next={eventsQuery.data?.next}
                        prev={eventsQuery.data?.prev}
                        onLimitChange={(value) => {
                            setLimit(value);
                            setCursor(null);
                        }}
                        onPage={setCursor}
                    />
                </div>
            </Card>
        </section>
    );
}

function AuthenticationEventFilter({
    onSearch,
}: {
    onSearch: (filters: ListAuthenticationEventsParams) => void;
}) {
    const [form] = Form.useForm<{
        eventType?: string;
        username?: string;
        keyword?: string;
        occurredRange?: [Dayjs, Dayjs];
    }>();

    function submit() {
        const values = form.getFieldsValue();
        onSearch({
            eventType: values.eventType,
            username: values.username?.trim(),
            keyword: values.keyword?.trim(),
            occurredAfter: values.occurredRange?.[0]?.format("YYYY-MM-DDTHH:mm:ss"),
            occurredBefore: values.occurredRange?.[1]?.format("YYYY-MM-DDTHH:mm:ss"),
        });
    }

    function reset() {
        form.resetFields();
        onSearch({});
    }

    return (
        <Form form={form} layout="inline" onFinish={submit}>
            <Form.Item name="eventType">
                <Select
                    allowClear
                    placeholder="事件类型"
                    style={{ width: 140 }}
                    options={eventTypeOptions}
                />
            </Form.Item>
            <Form.Item name="username">
                <Input allowClear placeholder="账号" style={{ width: 160 }} />
            </Form.Item>
            <Form.Item name="keyword">
                <Input allowClear placeholder="关键字" style={{ width: 220 }} />
            </Form.Item>
            <Form.Item name="occurredRange">
                <RangePicker showTime />
            </Form.Item>
            <Form.Item>
                <Space>
                    <Button icon={<SearchOutlined />} type="primary" htmlType="submit">
                        查询
                    </Button>
                    <Button onClick={reset}>重置</Button>
                </Space>
            </Form.Item>
        </Form>
    );
}

function eventLabel(eventType: string) {
    return eventTypeOptions.find((option) => option.value === eventType)?.label ?? eventType;
}

function eventColor(eventType: string) {
    if (eventType === "login_success") {
        return "green";
    }
    if (eventType === "login_failure") {
        return "red";
    }
    if (eventType === "kickout") {
        return "orange";
    }
    return "default";
}

function clientSummary(row: AuthenticationEventDto) {
    return (
        [row.client.browserName, row.client.osName, row.client.deviceType]
            .filter(Boolean)
            .join(" / ") || "-"
    );
}

function formatDateTime(value?: string | null) {
    return value ? value.replace("T", " ") : "-";
}
