// frontend/admin/src/pages/archive-library/ArchiveLibraryPage.vue
<script setup lang="ts">
import { ElMessage } from "element-plus";
import { onBeforeUnmount, onMounted, reactive, ref, watch } from "vue";

import { discoverArchiveRecords } from "@/shared/api/archive-records";
import {
    listArchiveCategories,
    listArchiveFields,
    listArchiveRelatedFilterCategories,
} from "@/shared/api/archive-metadata";
import type { ArchiveCategoryDto, ArchiveFieldDto } from "@/shared/types/archive-metadata";
import type { ArchiveRelatedFilterCategoryDto } from "@/shared/types/archive-records";
import CursorPagination from "@/shared/components/CursorPagination.vue";
import RequestErrorState from "@/shared/components/RequestErrorState.vue";
import { useArchiveQueryResult } from "@/shared/archive/query/useArchiveQueryResult";

import ArchiveAdvancedQueryPanel from "@/shared/archive/query/ArchiveAdvancedQueryPanel.vue";
import type { ArchiveQueryFormValues } from "@/shared/archive/query/archiveQueryTypes";
import ArchiveResultTable from "@/shared/archive/result-table/ArchiveResultTable.vue";
import { toSearchQuery } from "@/shared/archive/query/archiveQuery";

const form = reactive<ArchiveQueryFormValues>({ conditions: [], relatedGroups: [] });
const categories = ref<ArchiveCategoryDto[]>([]);
const fields = ref<ArchiveFieldDto[]>([]);
const relatedCategories = ref<ArchiveRelatedFilterCategoryDto[]>([]);
const relatedFieldsByCategory = ref(new Map<number, ArchiveFieldDto[]>());
const {
    result,
    orderBy,
    limit,
    loading,
    loadError,
    refresh,
    page,
    limitChange,
    orderResults,
    submit: submitQuery,
    reset: resetResults,
} = useArchiveQueryResult(discoverArchiveRecords);
let categoryLoadVersion = 0;
let disposed = false;

onBeforeUnmount(() => {
    disposed = true;
    categoryLoadVersion += 1;
});

onMounted(async () => {
    try {
        const response = await listArchiveCategories(true);
        if (!disposed) categories.value = response.items;
    } catch (error) {
        ElMessage.error(error instanceof Error ? error.message : "加载档案分类失败");
    }
});
watch(
    () => form.categoryId,
    async (categoryId, previous) => {
        const loadVersion = ++categoryLoadVersion;
        if (typeof categoryId !== "number") {
            fields.value = [];
            relatedCategories.value = [];
            relatedFieldsByCategory.value = new Map();
            return;
        }
        if (previous !== undefined && previous !== categoryId) {
            form.conditions = [];
            form.fondsCode = undefined;
            form.keyword = undefined;
            fields.value = [];
            relatedCategories.value = [];
            relatedFieldsByCategory.value = new Map();
        }
        try {
            const [fieldResponse, relatedResponse] = await Promise.all([
                listArchiveFields(categoryId, "ITEM"),
                listArchiveRelatedFilterCategories(categoryId),
            ]);
            const ids = [
                ...new Set(
                    relatedResponse.items
                        .map((item) => item.categoryId)
                        .filter((id): id is number => typeof id === "number"),
                ),
            ];
            const responses = await Promise.all(ids.map((id) => listArchiveFields(id, "ITEM")));
            if (disposed || loadVersion !== categoryLoadVersion || form.categoryId !== categoryId)
                return;
            fields.value = fieldResponse.items;
            relatedCategories.value = relatedResponse.items;
            relatedFieldsByCategory.value = new Map(
                ids.map((id, index) => [id, responses[index]!.items]),
            );
        } catch (error) {
            if (disposed || loadVersion !== categoryLoadVersion) return;
            fields.value = [];
            relatedCategories.value = [];
            relatedFieldsByCategory.value = new Map();
            ElMessage.error(error instanceof Error ? error.message : "加载查询字段失败");
        }
    },
);
function submit(values: ArchiveQueryFormValues) {
    submitQuery(toSearchQuery(values));
}
function reset() {
    resetResults();
    Object.assign(form, {
        categoryId: undefined,
        fondsCode: undefined,
        keyword: undefined,
        conditions: [],
        relatedGroups: [],
    });
}
</script>

<template>
    <section class="am-page">
        <div class="am-page__header"><h1>档案搜索</h1></div>
        <el-collapse class="am-page__filter am-query-collapse" :model-value="['query']"
            ><el-collapse-item name="query" title="高级筛选条件"
                ><ArchiveAdvancedQueryPanel
                    :model-value="form"
                    @update:model-value="Object.assign(form, $event)"
                    :categories="categories"
                    :fields="fields"
                    :related-categories="relatedCategories"
                    :related-fields-by-category="relatedFieldsByCategory"
                    show-keyword
                    :submitting="loading"
                    @reset="reset"
                    @submit="submit" /></el-collapse-item
        ></el-collapse>
        <el-card class="am-page__result" shadow="never"
            ><RequestErrorState
                v-if="loadError"
                :message="loadError"
                :retrying="loading"
                @retry="refresh" /><ArchiveResultTable
                v-if="result"
                :result="result"
                :loading="loading"
                :order-by="orderBy"
                @order-change="orderResults" /><el-empty
                v-else-if="!loadError"
                description="选择分类并提交高级查询后显示结果" />
            <div v-if="result" class="am-table-footer">
                <CursorPagination
                    :limit="limit"
                    :total="result.total"
                    :prev="result.prev"
                    :next="result.next"
                    :loading="loading"
                    @page="page"
                    @limit-change="limitChange"
                /></div
        ></el-card>
    </section>
</template>

// web/src/pages/archive-library/ArchiveLibraryPage.tsx
import { useMutation, useQueries, useQuery } from "@tanstack/react-query";
import { Card, Collapse, Empty, Form, Typography, message } from "antd";
import { useEffect, useRef, useState } from "react";

import {
    discoverArchiveRecords,
    listArchiveCategories,
    listArchiveFields,
    listArchiveRelatedFilterCategories,
} from "@/shared/api/archive";
import type {
    ArchiveFieldDto,
    ArchiveRecordOrderBy,
    ArchiveRecordQuery,
} from "@/shared/types/archive";

import {
    ArchiveAdvancedQueryPanel,
    type ArchiveQueryFormValues,
} from "./ArchiveAdvancedQueryPanel";
import { ArchiveResultTable } from "./ArchiveResultTable";
import { toSearchQuery } from "./archiveQuery";

export function ArchiveLibraryPage() {
    const [form] = Form.useForm<ArchiveQueryFormValues>();
    const [committedQuery, setCommittedQuery] = useState<ArchiveRecordQuery>();
    const [orderBy, setOrderBy] = useState<ArchiveRecordOrderBy[]>([]);
    const previousCategoryIdRef = useRef<number | undefined>(undefined);
    const categoriesQuery = useQuery({
        queryKey: ["archive-categories", "enabled"],
        queryFn: () => listArchiveCategories(true),
    });
    const categoryId = Form.useWatch("categoryId", form);
    const fieldsQuery = useQuery({
        enabled: typeof categoryId === "number",
        queryKey: ["archive-fields", categoryId, "ITEM"],
        queryFn: () => listArchiveFields(categoryId as number, "ITEM"),
    });
    const relatedCategoriesQuery = useQuery({
        enabled: typeof categoryId === "number",
        queryKey: ["archive-related-filter-categories", categoryId],
        queryFn: () => listArchiveRelatedFilterCategories(categoryId as number),
    });

    const relatedCategories = relatedCategoriesQuery.data?.items ?? [];
    const relatedFieldQueries = useQueries({
        queries: uniqueCategoryIds(relatedCategories).map((id) => ({
            enabled: typeof id === "number",
            queryKey: ["archive-fields", id, "ITEM"],
            queryFn: () => listArchiveFields(id, "ITEM"),
        })),
    });
    const relatedFieldsByCategory = new Map<number, ArchiveFieldDto[]>();
    uniqueCategoryIds(relatedCategories).forEach((id, index) => {
        relatedFieldsByCategory.set(id, relatedFieldQueries[index]?.data?.items ?? []);
    });

    const searchMutation = useMutation({
        mutationFn: (query: ArchiveRecordQuery) => discoverArchiveRecords(query),
        onError: (error) => {
            void message.error(error instanceof Error ? error.message : "查询失败");
        },
    });

    useEffect(() => {
        if (typeof categoryId !== "number") {
            previousCategoryIdRef.current = undefined;
            return;
        }

        const previousCategoryId = previousCategoryIdRef.current;
        previousCategoryIdRef.current = categoryId;
        if (previousCategoryId === undefined || previousCategoryId === categoryId) {
            return;
        }

        form.resetFields(["conditions", "fondsCode", "keyword", "relatedGroups"]);
        form.setFieldsValue({ categoryId, conditions: [], relatedGroups: [] });
        setCommittedQuery(undefined);
        setOrderBy([]);
        searchMutation.reset();
    }, [categoryId, form, searchMutation]);

    function submit(values: ArchiveQueryFormValues) {
        const query = toSearchQuery(values);
        setCommittedQuery(query);
        setOrderBy([]);
        searchMutation.mutate(query);
    }

    function orderResults(nextOrderBy: ArchiveRecordOrderBy[]) {
        if (!committedQuery) {
            return;
        }
        setOrderBy(nextOrderBy);
        searchMutation.mutate({
            ...committedQuery,
            orderBy: nextOrderBy.length > 0 ? nextOrderBy : undefined,
        });
    }

    function reset() {
        form.resetFields();
        setCommittedQuery(undefined);
        setOrderBy([]);
        searchMutation.reset();
    }

    const result = searchMutation.data;
    const fields = fieldsQuery.data?.items ?? result?.fields ?? [];

    return (
        <section className="am-page">
            <div className="am-page__header">
                <Typography.Title level={1}>档案搜索</Typography.Title>
            </div>
            <Collapse
                className="am-page__filter am-query-collapse"
                defaultActiveKey={["query"]}
                items={[
                    {
                        key: "query",
                        label: "高级筛选条件",
                        children: (
                            <ArchiveAdvancedQueryPanel
                                categories={categoriesQuery.data?.items ?? []}
                                fields={fields}
                                form={form}
                                relatedCategories={relatedCategories}
                                relatedFieldsByCategory={relatedFieldsByCategory}
                                showKeyword
                                submitting={searchMutation.isPending}
                                onReset={reset}
                                onSubmit={submit}
                            />
                        ),
                    },
                ]}
            />
            <Card className="am-page__result">
                {result ? (
                    <ArchiveResultTable
                        result={result}
                        loading={searchMutation.isPending}
                        orderBy={orderBy}
                        onOrderChange={orderResults}
                    />
                ) : (
                    <Empty description="选择分类并提交高级查询后显示结果" />
                )}
            </Card>
        </section>
    );
}

function uniqueCategoryIds(groups: Array<{ categoryId?: number }>) {
    return [...new Set(groups.map((group) => group.categoryId).filter(isNumber))];
}

function isNumber(value: unknown): value is number {
    return typeof value === "number";
}
