// apps/web/src/pages/placeholder/PlaceholderPage.tsx
import { Card, Typography } from "antd";

export function PlaceholderPage({ title }: { title: string }) {
    return (
        <section className="am-page">
            <div className="am-page__header">
                <Typography.Title level={1}>{title}</Typography.Title>
            </div>
            <Card>
                <Typography.Text type="secondary">该功能入口已接入 React 主壳。</Typography.Text>
            </Card>
        </section>
    );
}

// web/src/pages/placeholder/PlaceholderPage.vue
<script setup lang="ts">
defineProps<{ title: string }>();
</script>

<template>
    <section class="am-page">
        <div class="am-page__header">
            <h1>{{ title }}</h1>
        </div>
        <el-card shadow="never"><el-text type="info">该功能入口已接入 Vue 主壳。</el-text></el-card>
    </section>
</template>
